name: Generate Snake

on:
  push:
    branches:
      - main 
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create output directory
        run: mkdir -p output  # Создание директории output

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            output/github-contribution-grid-snake.svg  # Измените путь на output/
            color_snake: "#daf900"  
            color_dots: "#00FF00" 

      - name: Push generated files
        uses: actions/upload-artifact@v4
        with:
          name: snake
          path: output/github-contribution-grid-snake.svg  # Измените путь на output/

